favicon: null
name: sister naomi
opengraph:
  image: null
  type: null
  appId: null
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
purpose: []
color:
  saturation: 0.6610276
  brandStrength: 0.410401
  lightness: 0.4774436
  brandColors:
    - '#FFFFFF'
    - '#1F1D21'
    - '#A4A4A4'
    - '#888077'
    - '#6E391F'
  rhythmicContrast: 0.6691729
typography_spectrum: 0.3404851
layout_spectrum: 0.6450559
analytics:
  twitter: null
  google: null
  facebook: null
cta:
  bucket: null
  version: null
  domain: null
